// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "fir_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fir_hw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fir_hw::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> fir_hw::ap_ST_st1_fsm_0 = "1";
const sc_lv<9> fir_hw::ap_ST_st2_fsm_1 = "10";
const sc_lv<9> fir_hw::ap_ST_st3_fsm_2 = "100";
const sc_lv<9> fir_hw::ap_ST_st4_fsm_3 = "1000";
const sc_lv<9> fir_hw::ap_ST_st5_fsm_4 = "10000";
const sc_lv<9> fir_hw::ap_ST_st6_fsm_5 = "100000";
const sc_lv<9> fir_hw::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<9> fir_hw::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<9> fir_hw::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<32> fir_hw::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> fir_hw::ap_const_lv1_1 = "1";
const sc_lv<32> fir_hw::ap_const_lv32_1 = "1";
const sc_lv<1> fir_hw::ap_const_lv1_0 = "0";
const sc_lv<32> fir_hw::ap_const_lv32_3 = "11";
const sc_lv<32> fir_hw::ap_const_lv32_4 = "100";
const sc_lv<32> fir_hw::ap_const_lv32_6 = "110";
const sc_lv<32> fir_hw::ap_const_lv32_7 = "111";
const sc_lv<7> fir_hw::ap_const_lv7_0 = "0000000";
const sc_lv<32> fir_hw::ap_const_lv32_2 = "10";
const sc_lv<39> fir_hw::ap_const_lv39_0 = "000000000000000000000000000000000000000";
const sc_lv<8> fir_hw::ap_const_lv8_0 = "00000000";
const sc_lv<32> fir_hw::ap_const_lv32_8 = "1000";
const sc_lv<7> fir_hw::ap_const_lv7_7F = "1111111";
const sc_lv<7> fir_hw::ap_const_lv7_1 = "1";
const sc_lv<8> fir_hw::ap_const_lv8_80 = "10000000";
const sc_lv<8> fir_hw::ap_const_lv8_1 = "1";
const sc_lv<32> fir_hw::ap_const_lv32_10 = "10000";
const sc_lv<16> fir_hw::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> fir_hw::ap_const_lv32_11 = "10001";
const sc_lv<32> fir_hw::ap_const_lv32_22 = "100010";
const sc_lv<32> fir_hw::ap_const_lv32_23 = "100011";
const sc_lv<32> fir_hw::ap_const_lv32_24 = "100100";
const sc_lv<32> fir_hw::ap_const_lv32_26 = "100110";
const sc_lv<3> fir_hw::ap_const_lv3_7 = "111";
const sc_lv<4> fir_hw::ap_const_lv4_F = "1111";
const sc_lv<4> fir_hw::ap_const_lv4_0 = "0000";
const sc_lv<17> fir_hw::ap_const_lv17_0 = "00000000000000000";
const sc_lv<18> fir_hw::ap_const_lv18_1FFFF = "11111111111111111";
const sc_lv<18> fir_hw::ap_const_lv18_20001 = "100000000000000001";

fir_hw::fir_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {
    smpl_V_U = new fir_hw_smpl_V("smpl_V_U");
    smpl_V_U->clk(ap_clk);
    smpl_V_U->reset(ap_rst);
    smpl_V_U->address0(smpl_V_address0);
    smpl_V_U->ce0(smpl_V_ce0);
    smpl_V_U->we0(smpl_V_we0);
    smpl_V_U->d0(smpl_V_d0);
    smpl_V_U->q0(smpl_V_q0);
    coeff_hw_V_U = new fir_hw_coeff_hw_V("coeff_hw_V_U");
    coeff_hw_V_U->clk(ap_clk);
    coeff_hw_V_U->reset(ap_rst);
    coeff_hw_V_U->address0(coeff_hw_V_address0);
    coeff_hw_V_U->ce0(coeff_hw_V_ce0);
    coeff_hw_V_U->q0(coeff_hw_V_q0);
    fir_hw_mul_18s_15s_33_3_U0 = new fir_hw_mul_18s_15s_33_3<1,3,18,15,33>("fir_hw_mul_18s_15s_33_3_U0");
    fir_hw_mul_18s_15s_33_3_U0->clk(ap_clk);
    fir_hw_mul_18s_15s_33_3_U0->reset(ap_rst);
    fir_hw_mul_18s_15s_33_3_U0->din0(grp_fu_263_p0);
    fir_hw_mul_18s_15s_33_3_U0->din1(grp_fu_263_p1);
    fir_hw_mul_18s_15s_33_3_U0->ce(grp_fu_263_ce);
    fir_hw_mul_18s_15s_33_3_U0->dout(grp_fu_263_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Range1_all_ones_fu_360_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_4_fu_350_p4 );

    SC_METHOD(thread_Range1_all_zeros_fu_366_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_4_fu_350_p4 );

    SC_METHOD(thread_Range2_all_ones_fu_344_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_9_fu_334_p4 );

    SC_METHOD(thread_accu_V_fu_273_p2);
    sensitive << ( p_Val2_s_reg_154 );
    sensitive << ( tmp_9_cast_fu_269_p1 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_ap_sig_bdd_105);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_114);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_133);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_154);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_59);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_74);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_94);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_25 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_59 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_133 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_74 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_94 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_105 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_114 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_154 );

    SC_METHOD(thread_brmerge40_demorgan_i_fu_418_p2);
    sensitive << ( newsignbit_fu_306_p3 );
    sensitive << ( deleted_ones_fu_392_p3 );

    SC_METHOD(thread_brmerge40_i_fu_424_p2);
    sensitive << ( brmerge40_demorgan_i_fu_418_p2 );

    SC_METHOD(thread_brmerge_fu_493_p2);
    sensitive << ( overflow_fu_465_p2 );
    sensitive << ( underflow_2_not_fu_487_p2 );

    SC_METHOD(thread_brmerge_i_fu_412_p2);
    sensitive << ( newsignbit_fu_306_p3 );
    sensitive << ( p_not_i_fu_406_p2 );

    SC_METHOD(thread_brmerge_i_i_fu_481_p2);
    sensitive << ( underflow_fu_475_p2 );
    sensitive << ( overflow_fu_465_p2 );

    SC_METHOD(thread_carry_fu_320_p2);
    sensitive << ( tmp_15_fu_289_p3 );
    sensitive << ( tmp_6_fu_314_p2 );

    SC_METHOD(thread_coeff_hw_V_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_1_fu_211_p1 );

    SC_METHOD(thread_coeff_hw_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_deleted_ones_fu_392_p3);
    sensitive << ( carry_fu_320_p2 );
    sensitive << ( Range1_all_ones_fu_360_p2 );
    sensitive << ( p_41_i_fu_386_p2 );

    SC_METHOD(thread_deleted_zeros_fu_372_p3);
    sensitive << ( carry_fu_320_p2 );
    sensitive << ( Range1_all_ones_fu_360_p2 );
    sensitive << ( Range1_all_zeros_fu_366_p2 );

    SC_METHOD(thread_exitcond1_fu_177_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_142 );

    SC_METHOD(thread_exitcond_fu_199_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( i1_reg_166 );

    SC_METHOD(thread_grp_fu_263_ce);

    SC_METHOD(thread_grp_fu_263_p0);
    sensitive << ( smpl_V_q0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_grp_fu_263_p1);
    sensitive << ( coeff_hw_V_q0 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_i_1_fu_183_p2);
    sensitive << ( i_reg_142 );

    SC_METHOD(thread_i_2_fu_205_p2);
    sensitive << ( i1_reg_166 );

    SC_METHOD(thread_newsignbit_fu_306_p3);
    sensitive << ( p_Val2_2_fu_300_p2 );

    SC_METHOD(thread_overflow_fu_465_p2);
    sensitive << ( brmerge_i_reg_584 );
    sensitive << ( tmp_3_fu_459_p2 );

    SC_METHOD(thread_p_38_i_fu_400_p2);
    sensitive << ( carry_fu_320_p2 );
    sensitive << ( Range1_all_ones_fu_360_p2 );

    SC_METHOD(thread_p_41_i_fu_386_p2);
    sensitive << ( Range2_all_ones_fu_344_p2 );
    sensitive << ( tmp_7_fu_380_p2 );

    SC_METHOD(thread_p_Val2_1_fu_279_p4);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_p_Val2_2_fu_300_p2);
    sensitive << ( p_Val2_1_fu_279_p4 );
    sensitive << ( tmp_s_fu_297_p1 );

    SC_METHOD(thread_p_Val2_5_fu_506_p3);
    sensitive << ( p_Val2_2_reg_573 );
    sensitive << ( underflow_fu_475_p2 );

    SC_METHOD(thread_p_Val2_5_mux_fu_499_p3);
    sensitive << ( p_Val2_2_reg_573 );
    sensitive << ( brmerge_i_i_fu_481_p2 );

    SC_METHOD(thread_p_not_i_fu_406_p2);
    sensitive << ( deleted_zeros_fu_372_p3 );

    SC_METHOD(thread_qb_assign_1_fu_249_p2);
    sensitive << ( r_i_i_fu_243_p2 );
    sensitive << ( qbit_fu_217_p3 );

    SC_METHOD(thread_qbit_fu_217_p3);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_r_fu_229_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( exitcond_fu_199_p2 );
    sensitive << ( tmp_14_fu_225_p1 );

    SC_METHOD(thread_r_i_i_fu_243_p2);
    sensitive << ( tmp_16_fu_235_p3 );
    sensitive << ( r_fu_229_p2 );

    SC_METHOD(thread_res_V);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( brmerge_fu_493_p2 );
    sensitive << ( p_Val2_5_mux_fu_499_p3 );
    sensitive << ( p_Val2_5_fu_506_p3 );

    SC_METHOD(thread_res_V_ap_vld);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_signbit_fu_446_p3);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_smpl_V_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_177_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_2_fu_189_p1 );
    sensitive << ( tmp_fu_194_p1 );
    sensitive << ( tmp_1_fu_211_p1 );

    SC_METHOD(thread_smpl_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_177_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_smpl_V_d0);
    sensitive << ( input_V );
    sensitive << ( smpl_V_q0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_177_p2 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_smpl_V_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_177_p2 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_tmp2_fu_470_p2);
    sensitive << ( tmp_10_reg_589 );
    sensitive << ( tmp_8_fu_454_p2 );

    SC_METHOD(thread_tmp_10_fu_440_p2);
    sensitive << ( tmp_5_fu_434_p2 );
    sensitive << ( brmerge40_i_fu_424_p2 );

    SC_METHOD(thread_tmp_14_fu_225_p1);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_tmp_15_fu_289_p3);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_tmp_16_fu_235_p3);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_tmp_18_fu_326_p3);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_tmp_19_fu_430_p1);
    sensitive << ( p_Val2_2_fu_300_p2 );

    SC_METHOD(thread_tmp_1_fu_211_p1);
    sensitive << ( i1_reg_166 );

    SC_METHOD(thread_tmp_2_fu_189_p1);
    sensitive << ( i_1_fu_183_p2 );

    SC_METHOD(thread_tmp_3_fu_459_p2);
    sensitive << ( signbit_fu_446_p3 );

    SC_METHOD(thread_tmp_4_fu_350_p4);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_tmp_5_fu_434_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_19_fu_430_p1 );

    SC_METHOD(thread_tmp_6_fu_314_p2);
    sensitive << ( newsignbit_fu_306_p3 );

    SC_METHOD(thread_tmp_7_fu_380_p2);
    sensitive << ( tmp_18_fu_326_p3 );

    SC_METHOD(thread_tmp_8_fu_454_p2);
    sensitive << ( p_38_i_reg_579 );

    SC_METHOD(thread_tmp_9_cast_fu_269_p1);
    sensitive << ( grp_fu_263_p2 );

    SC_METHOD(thread_tmp_9_fu_334_p4);
    sensitive << ( p_Val2_s_reg_154 );

    SC_METHOD(thread_tmp_fu_194_p1);
    sensitive << ( i_reg_142 );

    SC_METHOD(thread_tmp_s_fu_297_p1);
    sensitive << ( qb_assign_1_reg_553 );

    SC_METHOD(thread_underflow_2_not_fu_487_p2);
    sensitive << ( underflow_fu_475_p2 );

    SC_METHOD(thread_underflow_fu_475_p2);
    sensitive << ( signbit_fu_446_p3 );
    sensitive << ( tmp2_fu_470_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_177_p2 );
    sensitive << ( exitcond_fu_199_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fir_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_V, "(port)input_V");
    sc_trace(mVcdFile, res_V, "(port)res_V");
    sc_trace(mVcdFile, res_V_ap_vld, "(port)res_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_25, "ap_sig_bdd_25");
    sc_trace(mVcdFile, smpl_V_address0, "smpl_V_address0");
    sc_trace(mVcdFile, smpl_V_ce0, "smpl_V_ce0");
    sc_trace(mVcdFile, smpl_V_we0, "smpl_V_we0");
    sc_trace(mVcdFile, smpl_V_d0, "smpl_V_d0");
    sc_trace(mVcdFile, smpl_V_q0, "smpl_V_q0");
    sc_trace(mVcdFile, coeff_hw_V_address0, "coeff_hw_V_address0");
    sc_trace(mVcdFile, coeff_hw_V_ce0, "coeff_hw_V_ce0");
    sc_trace(mVcdFile, coeff_hw_V_q0, "coeff_hw_V_q0");
    sc_trace(mVcdFile, i_1_fu_183_p2, "i_1_fu_183_p2");
    sc_trace(mVcdFile, i_1_reg_525, "i_1_reg_525");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_59, "ap_sig_bdd_59");
    sc_trace(mVcdFile, exitcond1_fu_177_p2, "exitcond1_fu_177_p2");
    sc_trace(mVcdFile, i_2_fu_205_p2, "i_2_fu_205_p2");
    sc_trace(mVcdFile, i_2_reg_538, "i_2_reg_538");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_74, "ap_sig_bdd_74");
    sc_trace(mVcdFile, exitcond_fu_199_p2, "exitcond_fu_199_p2");
    sc_trace(mVcdFile, qb_assign_1_fu_249_p2, "qb_assign_1_fu_249_p2");
    sc_trace(mVcdFile, qb_assign_1_reg_553, "qb_assign_1_reg_553");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_94, "ap_sig_bdd_94");
    sc_trace(mVcdFile, accu_V_fu_273_p2, "accu_V_fu_273_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_105, "ap_sig_bdd_105");
    sc_trace(mVcdFile, p_Val2_2_fu_300_p2, "p_Val2_2_fu_300_p2");
    sc_trace(mVcdFile, p_Val2_2_reg_573, "p_Val2_2_reg_573");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_114, "ap_sig_bdd_114");
    sc_trace(mVcdFile, p_38_i_fu_400_p2, "p_38_i_fu_400_p2");
    sc_trace(mVcdFile, p_38_i_reg_579, "p_38_i_reg_579");
    sc_trace(mVcdFile, brmerge_i_fu_412_p2, "brmerge_i_fu_412_p2");
    sc_trace(mVcdFile, brmerge_i_reg_584, "brmerge_i_reg_584");
    sc_trace(mVcdFile, tmp_10_fu_440_p2, "tmp_10_fu_440_p2");
    sc_trace(mVcdFile, tmp_10_reg_589, "tmp_10_reg_589");
    sc_trace(mVcdFile, i_reg_142, "i_reg_142");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_133, "ap_sig_bdd_133");
    sc_trace(mVcdFile, p_Val2_s_reg_154, "p_Val2_s_reg_154");
    sc_trace(mVcdFile, i1_reg_166, "i1_reg_166");
    sc_trace(mVcdFile, tmp_2_fu_189_p1, "tmp_2_fu_189_p1");
    sc_trace(mVcdFile, tmp_fu_194_p1, "tmp_fu_194_p1");
    sc_trace(mVcdFile, tmp_1_fu_211_p1, "tmp_1_fu_211_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_154, "ap_sig_bdd_154");
    sc_trace(mVcdFile, tmp_14_fu_225_p1, "tmp_14_fu_225_p1");
    sc_trace(mVcdFile, tmp_16_fu_235_p3, "tmp_16_fu_235_p3");
    sc_trace(mVcdFile, r_fu_229_p2, "r_fu_229_p2");
    sc_trace(mVcdFile, r_i_i_fu_243_p2, "r_i_i_fu_243_p2");
    sc_trace(mVcdFile, qbit_fu_217_p3, "qbit_fu_217_p3");
    sc_trace(mVcdFile, grp_fu_263_p0, "grp_fu_263_p0");
    sc_trace(mVcdFile, grp_fu_263_p1, "grp_fu_263_p1");
    sc_trace(mVcdFile, grp_fu_263_p2, "grp_fu_263_p2");
    sc_trace(mVcdFile, tmp_9_cast_fu_269_p1, "tmp_9_cast_fu_269_p1");
    sc_trace(mVcdFile, p_Val2_1_fu_279_p4, "p_Val2_1_fu_279_p4");
    sc_trace(mVcdFile, tmp_s_fu_297_p1, "tmp_s_fu_297_p1");
    sc_trace(mVcdFile, newsignbit_fu_306_p3, "newsignbit_fu_306_p3");
    sc_trace(mVcdFile, tmp_15_fu_289_p3, "tmp_15_fu_289_p3");
    sc_trace(mVcdFile, tmp_6_fu_314_p2, "tmp_6_fu_314_p2");
    sc_trace(mVcdFile, tmp_9_fu_334_p4, "tmp_9_fu_334_p4");
    sc_trace(mVcdFile, tmp_4_fu_350_p4, "tmp_4_fu_350_p4");
    sc_trace(mVcdFile, carry_fu_320_p2, "carry_fu_320_p2");
    sc_trace(mVcdFile, Range1_all_ones_fu_360_p2, "Range1_all_ones_fu_360_p2");
    sc_trace(mVcdFile, Range1_all_zeros_fu_366_p2, "Range1_all_zeros_fu_366_p2");
    sc_trace(mVcdFile, tmp_18_fu_326_p3, "tmp_18_fu_326_p3");
    sc_trace(mVcdFile, Range2_all_ones_fu_344_p2, "Range2_all_ones_fu_344_p2");
    sc_trace(mVcdFile, tmp_7_fu_380_p2, "tmp_7_fu_380_p2");
    sc_trace(mVcdFile, p_41_i_fu_386_p2, "p_41_i_fu_386_p2");
    sc_trace(mVcdFile, deleted_zeros_fu_372_p3, "deleted_zeros_fu_372_p3");
    sc_trace(mVcdFile, p_not_i_fu_406_p2, "p_not_i_fu_406_p2");
    sc_trace(mVcdFile, deleted_ones_fu_392_p3, "deleted_ones_fu_392_p3");
    sc_trace(mVcdFile, brmerge40_demorgan_i_fu_418_p2, "brmerge40_demorgan_i_fu_418_p2");
    sc_trace(mVcdFile, tmp_19_fu_430_p1, "tmp_19_fu_430_p1");
    sc_trace(mVcdFile, tmp_5_fu_434_p2, "tmp_5_fu_434_p2");
    sc_trace(mVcdFile, brmerge40_i_fu_424_p2, "brmerge40_i_fu_424_p2");
    sc_trace(mVcdFile, signbit_fu_446_p3, "signbit_fu_446_p3");
    sc_trace(mVcdFile, tmp_3_fu_459_p2, "tmp_3_fu_459_p2");
    sc_trace(mVcdFile, tmp_8_fu_454_p2, "tmp_8_fu_454_p2");
    sc_trace(mVcdFile, tmp2_fu_470_p2, "tmp2_fu_470_p2");
    sc_trace(mVcdFile, underflow_fu_475_p2, "underflow_fu_475_p2");
    sc_trace(mVcdFile, overflow_fu_465_p2, "overflow_fu_465_p2");
    sc_trace(mVcdFile, underflow_2_not_fu_487_p2, "underflow_2_not_fu_487_p2");
    sc_trace(mVcdFile, brmerge_i_i_fu_481_p2, "brmerge_i_i_fu_481_p2");
    sc_trace(mVcdFile, brmerge_fu_493_p2, "brmerge_fu_493_p2");
    sc_trace(mVcdFile, p_Val2_5_mux_fu_499_p3, "p_Val2_5_mux_fu_499_p3");
    sc_trace(mVcdFile, p_Val2_5_fu_506_p3, "p_Val2_5_fu_506_p3");
    sc_trace(mVcdFile, grp_fu_263_ce, "grp_fu_263_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("fir_hw.hdltvin.dat");
    mHdltvoutHandle.open("fir_hw.hdltvout.dat");
}

fir_hw::~fir_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete smpl_V_U;
    delete coeff_hw_V_U;
    delete fir_hw_mul_18s_15s_33_3_U0;
}

void fir_hw::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        i1_reg_166 = i_2_reg_538.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0))) {
        i1_reg_166 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_reg_142 = i_1_reg_525.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_142 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        p_Val2_s_reg_154 = accu_V_fu_273_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0))) {
        p_Val2_s_reg_154 = ap_const_lv39_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        brmerge_i_reg_584 = brmerge_i_fu_412_p2.read();
        p_38_i_reg_579 = p_38_i_fu_400_p2.read();
        p_Val2_2_reg_573 = p_Val2_2_fu_300_p2.read();
        tmp_10_reg_589 = tmp_10_fu_440_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_1_reg_525 = i_1_fu_183_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        i_2_reg_538 = i_2_fu_205_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_199_p2.read()))) {
        qb_assign_1_reg_553 = qb_assign_1_fu_249_p2.read();
    }
}

void fir_hw::thread_Range1_all_ones_fu_360_p2() {
    Range1_all_ones_fu_360_p2 = (!tmp_4_fu_350_p4.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_350_p4.read() == ap_const_lv4_F);
}

void fir_hw::thread_Range1_all_zeros_fu_366_p2() {
    Range1_all_zeros_fu_366_p2 = (!tmp_4_fu_350_p4.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_350_p4.read() == ap_const_lv4_0);
}

void fir_hw::thread_Range2_all_ones_fu_344_p2() {
    Range2_all_ones_fu_344_p2 = (!tmp_9_fu_334_p4.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(tmp_9_fu_334_p4.read() == ap_const_lv3_7);
}

void fir_hw::thread_accu_V_fu_273_p2() {
    accu_V_fu_273_p2 = (!p_Val2_s_reg_154.read().is_01() || !tmp_9_cast_fu_269_p1.read().is_01())? sc_lv<39>(): (sc_biguint<39>(p_Val2_s_reg_154.read()) + sc_bigint<39>(tmp_9_cast_fu_269_p1.read()));
}

void fir_hw::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_sig_bdd_105() {
    ap_sig_bdd_105 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void fir_hw::thread_ap_sig_bdd_114() {
    ap_sig_bdd_114 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void fir_hw::thread_ap_sig_bdd_133() {
    ap_sig_bdd_133 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void fir_hw::thread_ap_sig_bdd_154() {
    ap_sig_bdd_154 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void fir_hw::thread_ap_sig_bdd_25() {
    ap_sig_bdd_25 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void fir_hw::thread_ap_sig_bdd_59() {
    ap_sig_bdd_59 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void fir_hw::thread_ap_sig_bdd_74() {
    ap_sig_bdd_74 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void fir_hw::thread_ap_sig_bdd_94() {
    ap_sig_bdd_94 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void fir_hw::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_25.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_59.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_133.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_74.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_94.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_105.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_114.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void fir_hw::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_154.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void fir_hw::thread_brmerge40_demorgan_i_fu_418_p2() {
    brmerge40_demorgan_i_fu_418_p2 = (newsignbit_fu_306_p3.read() & deleted_ones_fu_392_p3.read());
}

void fir_hw::thread_brmerge40_i_fu_424_p2() {
    brmerge40_i_fu_424_p2 = (brmerge40_demorgan_i_fu_418_p2.read() ^ ap_const_lv1_1);
}

void fir_hw::thread_brmerge_fu_493_p2() {
    brmerge_fu_493_p2 = (overflow_fu_465_p2.read() | underflow_2_not_fu_487_p2.read());
}

void fir_hw::thread_brmerge_i_fu_412_p2() {
    brmerge_i_fu_412_p2 = (newsignbit_fu_306_p3.read() | p_not_i_fu_406_p2.read());
}

void fir_hw::thread_brmerge_i_i_fu_481_p2() {
    brmerge_i_i_fu_481_p2 = (underflow_fu_475_p2.read() | overflow_fu_465_p2.read());
}

void fir_hw::thread_carry_fu_320_p2() {
    carry_fu_320_p2 = (tmp_15_fu_289_p3.read() & tmp_6_fu_314_p2.read());
}

void fir_hw::thread_coeff_hw_V_address0() {
    coeff_hw_V_address0 =  (sc_lv<7>) (tmp_1_fu_211_p1.read());
}

void fir_hw::thread_coeff_hw_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        coeff_hw_V_ce0 = ap_const_logic_1;
    } else {
        coeff_hw_V_ce0 = ap_const_logic_0;
    }
}

void fir_hw::thread_deleted_ones_fu_392_p3() {
    deleted_ones_fu_392_p3 = (!carry_fu_320_p2.read()[0].is_01())? sc_lv<1>(): ((carry_fu_320_p2.read()[0].to_bool())? p_41_i_fu_386_p2.read(): Range1_all_ones_fu_360_p2.read());
}

void fir_hw::thread_deleted_zeros_fu_372_p3() {
    deleted_zeros_fu_372_p3 = (!carry_fu_320_p2.read()[0].is_01())? sc_lv<1>(): ((carry_fu_320_p2.read()[0].to_bool())? Range1_all_ones_fu_360_p2.read(): Range1_all_zeros_fu_366_p2.read());
}

void fir_hw::thread_exitcond1_fu_177_p2() {
    exitcond1_fu_177_p2 = (!i_reg_142.read().is_01() || !ap_const_lv7_7F.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_142.read() == ap_const_lv7_7F);
}

void fir_hw::thread_exitcond_fu_199_p2() {
    exitcond_fu_199_p2 = (!i1_reg_166.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_166.read() == ap_const_lv8_80);
}

void fir_hw::thread_grp_fu_263_ce() {
    grp_fu_263_ce = ap_const_logic_1;
}

void fir_hw::thread_grp_fu_263_p0() {
    grp_fu_263_p0 = smpl_V_q0.read();
}

void fir_hw::thread_grp_fu_263_p1() {
    grp_fu_263_p1 = coeff_hw_V_q0.read();
}

void fir_hw::thread_i_1_fu_183_p2() {
    i_1_fu_183_p2 = (!i_reg_142.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_reg_142.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fir_hw::thread_i_2_fu_205_p2() {
    i_2_fu_205_p2 = (!i1_reg_166.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i1_reg_166.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void fir_hw::thread_newsignbit_fu_306_p3() {
    newsignbit_fu_306_p3 = p_Val2_2_fu_300_p2.read().range(17, 17);
}

void fir_hw::thread_overflow_fu_465_p2() {
    overflow_fu_465_p2 = (brmerge_i_reg_584.read() & tmp_3_fu_459_p2.read());
}

void fir_hw::thread_p_38_i_fu_400_p2() {
    p_38_i_fu_400_p2 = (carry_fu_320_p2.read() & Range1_all_ones_fu_360_p2.read());
}

void fir_hw::thread_p_41_i_fu_386_p2() {
    p_41_i_fu_386_p2 = (Range2_all_ones_fu_344_p2.read() & tmp_7_fu_380_p2.read());
}

void fir_hw::thread_p_Val2_1_fu_279_p4() {
    p_Val2_1_fu_279_p4 = p_Val2_s_reg_154.read().range(34, 17);
}

void fir_hw::thread_p_Val2_2_fu_300_p2() {
    p_Val2_2_fu_300_p2 = (!p_Val2_1_fu_279_p4.read().is_01() || !tmp_s_fu_297_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_Val2_1_fu_279_p4.read()) + sc_biguint<18>(tmp_s_fu_297_p1.read()));
}

void fir_hw::thread_p_Val2_5_fu_506_p3() {
    p_Val2_5_fu_506_p3 = (!underflow_fu_475_p2.read()[0].is_01())? sc_lv<18>(): ((underflow_fu_475_p2.read()[0].to_bool())? ap_const_lv18_20001: p_Val2_2_reg_573.read());
}

void fir_hw::thread_p_Val2_5_mux_fu_499_p3() {
    p_Val2_5_mux_fu_499_p3 = (!brmerge_i_i_fu_481_p2.read()[0].is_01())? sc_lv<18>(): ((brmerge_i_i_fu_481_p2.read()[0].to_bool())? ap_const_lv18_1FFFF: p_Val2_2_reg_573.read());
}

void fir_hw::thread_p_not_i_fu_406_p2() {
    p_not_i_fu_406_p2 = (deleted_zeros_fu_372_p3.read() ^ ap_const_lv1_1);
}

void fir_hw::thread_qb_assign_1_fu_249_p2() {
    qb_assign_1_fu_249_p2 = (r_i_i_fu_243_p2.read() & qbit_fu_217_p3.read());
}

void fir_hw::thread_qbit_fu_217_p3() {
    qbit_fu_217_p3 = p_Val2_s_reg_154.read().range(16, 16);
}

void fir_hw::thread_r_fu_229_p2() {
    r_fu_229_p2 = (!tmp_14_fu_225_p1.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_14_fu_225_p1.read() != ap_const_lv16_0);
}

void fir_hw::thread_r_i_i_fu_243_p2() {
    r_i_i_fu_243_p2 = (tmp_16_fu_235_p3.read() | r_fu_229_p2.read());
}

void fir_hw::thread_res_V() {
    res_V = (!brmerge_fu_493_p2.read()[0].is_01())? sc_lv<18>(): ((brmerge_fu_493_p2.read()[0].to_bool())? p_Val2_5_mux_fu_499_p3.read(): p_Val2_5_fu_506_p3.read());
}

void fir_hw::thread_res_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        res_V_ap_vld = ap_const_logic_1;
    } else {
        res_V_ap_vld = ap_const_logic_0;
    }
}

void fir_hw::thread_signbit_fu_446_p3() {
    signbit_fu_446_p3 = p_Val2_s_reg_154.read().range(38, 38);
}

void fir_hw::thread_smpl_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        smpl_V_address0 =  (sc_lv<7>) (tmp_fu_194_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0))) {
        smpl_V_address0 = ap_const_lv7_7F;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        smpl_V_address0 =  (sc_lv<7>) (tmp_1_fu_211_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0))) {
        smpl_V_address0 =  (sc_lv<7>) (tmp_2_fu_189_p1.read());
    } else {
        smpl_V_address0 = "XXXXXXX";
    }
}

void fir_hw::thread_smpl_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0)))) {
        smpl_V_ce0 = ap_const_logic_1;
    } else {
        smpl_V_ce0 = ap_const_logic_0;
    }
}

void fir_hw::thread_smpl_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        smpl_V_d0 = smpl_V_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0))) {
        smpl_V_d0 = input_V.read();
    } else {
        smpl_V_d0 =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
    }
}

void fir_hw::thread_smpl_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0)))) {
        smpl_V_we0 = ap_const_logic_1;
    } else {
        smpl_V_we0 = ap_const_logic_0;
    }
}

void fir_hw::thread_tmp2_fu_470_p2() {
    tmp2_fu_470_p2 = (tmp_10_reg_589.read() & tmp_8_fu_454_p2.read());
}

void fir_hw::thread_tmp_10_fu_440_p2() {
    tmp_10_fu_440_p2 = (tmp_5_fu_434_p2.read() | brmerge40_i_fu_424_p2.read());
}

void fir_hw::thread_tmp_14_fu_225_p1() {
    tmp_14_fu_225_p1 = p_Val2_s_reg_154.read().range(16-1, 0);
}

void fir_hw::thread_tmp_15_fu_289_p3() {
    tmp_15_fu_289_p3 = p_Val2_s_reg_154.read().range(34, 34);
}

void fir_hw::thread_tmp_16_fu_235_p3() {
    tmp_16_fu_235_p3 = p_Val2_s_reg_154.read().range(17, 17);
}

void fir_hw::thread_tmp_18_fu_326_p3() {
    tmp_18_fu_326_p3 = p_Val2_s_reg_154.read().range(35, 35);
}

void fir_hw::thread_tmp_19_fu_430_p1() {
    tmp_19_fu_430_p1 = p_Val2_2_fu_300_p2.read().range(17-1, 0);
}

void fir_hw::thread_tmp_1_fu_211_p1() {
    tmp_1_fu_211_p1 = esl_zext<64,8>(i1_reg_166.read());
}

void fir_hw::thread_tmp_2_fu_189_p1() {
    tmp_2_fu_189_p1 = esl_zext<64,7>(i_1_fu_183_p2.read());
}

void fir_hw::thread_tmp_3_fu_459_p2() {
    tmp_3_fu_459_p2 = (signbit_fu_446_p3.read() ^ ap_const_lv1_1);
}

void fir_hw::thread_tmp_4_fu_350_p4() {
    tmp_4_fu_350_p4 = p_Val2_s_reg_154.read().range(38, 35);
}

void fir_hw::thread_tmp_5_fu_434_p2() {
    tmp_5_fu_434_p2 = (!tmp_19_fu_430_p1.read().is_01() || !ap_const_lv17_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_19_fu_430_p1.read() == ap_const_lv17_0);
}

void fir_hw::thread_tmp_6_fu_314_p2() {
    tmp_6_fu_314_p2 = (newsignbit_fu_306_p3.read() ^ ap_const_lv1_1);
}

void fir_hw::thread_tmp_7_fu_380_p2() {
    tmp_7_fu_380_p2 = (tmp_18_fu_326_p3.read() ^ ap_const_lv1_1);
}

void fir_hw::thread_tmp_8_fu_454_p2() {
    tmp_8_fu_454_p2 = (p_38_i_reg_579.read() ^ ap_const_lv1_1);
}

void fir_hw::thread_tmp_9_cast_fu_269_p1() {
    tmp_9_cast_fu_269_p1 = esl_sext<39,33>(grp_fu_263_p2.read());
}

void fir_hw::thread_tmp_9_fu_334_p4() {
    tmp_9_fu_334_p4 = p_Val2_s_reg_154.read().range(38, 36);
}

void fir_hw::thread_tmp_fu_194_p1() {
    tmp_fu_194_p1 = esl_zext<64,7>(i_reg_142.read());
}

void fir_hw::thread_tmp_s_fu_297_p1() {
    tmp_s_fu_297_p1 = esl_zext<18,1>(qb_assign_1_reg_553.read());
}

void fir_hw::thread_underflow_2_not_fu_487_p2() {
    underflow_2_not_fu_487_p2 = (underflow_fu_475_p2.read() ^ ap_const_lv1_1);
}

void fir_hw::thread_underflow_fu_475_p2() {
    underflow_fu_475_p2 = (tmp2_fu_470_p2.read() & signbit_fu_446_p3.read());
}

void fir_hw::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond1_fu_177_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_199_p2.read())) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

void fir_hw::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_V\" :  \"" << input_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_V\" :  \"" << res_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_V_ap_vld\" :  \"" << res_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

