// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _fir_hw_HH_
#define _fir_hw_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "fir_hw_mul_18s_15s_33_3.h"
#include "fir_hw_smpl_V.h"
#include "fir_hw_coeff_hw_V.h"

namespace ap_rtl {

struct fir_hw : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<18> > input_V;
    sc_out< sc_lv<18> > res_V;
    sc_out< sc_logic > res_V_ap_vld;


    // Module declarations
    fir_hw(sc_module_name name);
    SC_HAS_PROCESS(fir_hw);

    ~fir_hw();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    fir_hw_smpl_V* smpl_V_U;
    fir_hw_coeff_hw_V* coeff_hw_V_U;
    fir_hw_mul_18s_15s_33_3<1,3,18,15,33>* fir_hw_mul_18s_15s_33_3_U0;
    sc_signal< sc_lv<9> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_25;
    sc_signal< sc_lv<7> > smpl_V_address0;
    sc_signal< sc_logic > smpl_V_ce0;
    sc_signal< sc_logic > smpl_V_we0;
    sc_signal< sc_lv<18> > smpl_V_d0;
    sc_signal< sc_lv<18> > smpl_V_q0;
    sc_signal< sc_lv<7> > coeff_hw_V_address0;
    sc_signal< sc_logic > coeff_hw_V_ce0;
    sc_signal< sc_lv<15> > coeff_hw_V_q0;
    sc_signal< sc_lv<7> > i_1_fu_183_p2;
    sc_signal< sc_lv<7> > i_1_reg_525;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_59;
    sc_signal< sc_lv<1> > exitcond1_fu_177_p2;
    sc_signal< sc_lv<8> > i_2_fu_205_p2;
    sc_signal< sc_lv<8> > i_2_reg_538;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_74;
    sc_signal< sc_lv<1> > exitcond_fu_199_p2;
    sc_signal< sc_lv<1> > qb_assign_1_fu_249_p2;
    sc_signal< sc_lv<1> > qb_assign_1_reg_553;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_94;
    sc_signal< sc_lv<39> > accu_V_fu_273_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_bdd_105;
    sc_signal< sc_lv<18> > p_Val2_2_fu_300_p2;
    sc_signal< sc_lv<18> > p_Val2_2_reg_573;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_bdd_114;
    sc_signal< sc_lv<1> > p_38_i_fu_400_p2;
    sc_signal< sc_lv<1> > p_38_i_reg_579;
    sc_signal< sc_lv<1> > brmerge_i_fu_412_p2;
    sc_signal< sc_lv<1> > brmerge_i_reg_584;
    sc_signal< sc_lv<1> > tmp_10_fu_440_p2;
    sc_signal< sc_lv<1> > tmp_10_reg_589;
    sc_signal< sc_lv<7> > i_reg_142;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_133;
    sc_signal< sc_lv<39> > p_Val2_s_reg_154;
    sc_signal< sc_lv<8> > i1_reg_166;
    sc_signal< sc_lv<64> > tmp_2_fu_189_p1;
    sc_signal< sc_lv<64> > tmp_fu_194_p1;
    sc_signal< sc_lv<64> > tmp_1_fu_211_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_bdd_154;
    sc_signal< sc_lv<16> > tmp_14_fu_225_p1;
    sc_signal< sc_lv<1> > tmp_16_fu_235_p3;
    sc_signal< sc_lv<1> > r_fu_229_p2;
    sc_signal< sc_lv<1> > r_i_i_fu_243_p2;
    sc_signal< sc_lv<1> > qbit_fu_217_p3;
    sc_signal< sc_lv<18> > grp_fu_263_p0;
    sc_signal< sc_lv<15> > grp_fu_263_p1;
    sc_signal< sc_lv<33> > grp_fu_263_p2;
    sc_signal< sc_lv<39> > tmp_9_cast_fu_269_p1;
    sc_signal< sc_lv<18> > p_Val2_1_fu_279_p4;
    sc_signal< sc_lv<18> > tmp_s_fu_297_p1;
    sc_signal< sc_lv<1> > newsignbit_fu_306_p3;
    sc_signal< sc_lv<1> > tmp_15_fu_289_p3;
    sc_signal< sc_lv<1> > tmp_6_fu_314_p2;
    sc_signal< sc_lv<3> > tmp_9_fu_334_p4;
    sc_signal< sc_lv<4> > tmp_4_fu_350_p4;
    sc_signal< sc_lv<1> > carry_fu_320_p2;
    sc_signal< sc_lv<1> > Range1_all_ones_fu_360_p2;
    sc_signal< sc_lv<1> > Range1_all_zeros_fu_366_p2;
    sc_signal< sc_lv<1> > tmp_18_fu_326_p3;
    sc_signal< sc_lv<1> > Range2_all_ones_fu_344_p2;
    sc_signal< sc_lv<1> > tmp_7_fu_380_p2;
    sc_signal< sc_lv<1> > p_41_i_fu_386_p2;
    sc_signal< sc_lv<1> > deleted_zeros_fu_372_p3;
    sc_signal< sc_lv<1> > p_not_i_fu_406_p2;
    sc_signal< sc_lv<1> > deleted_ones_fu_392_p3;
    sc_signal< sc_lv<1> > brmerge40_demorgan_i_fu_418_p2;
    sc_signal< sc_lv<17> > tmp_19_fu_430_p1;
    sc_signal< sc_lv<1> > tmp_5_fu_434_p2;
    sc_signal< sc_lv<1> > brmerge40_i_fu_424_p2;
    sc_signal< sc_lv<1> > signbit_fu_446_p3;
    sc_signal< sc_lv<1> > tmp_3_fu_459_p2;
    sc_signal< sc_lv<1> > tmp_8_fu_454_p2;
    sc_signal< sc_lv<1> > tmp2_fu_470_p2;
    sc_signal< sc_lv<1> > underflow_fu_475_p2;
    sc_signal< sc_lv<1> > overflow_fu_465_p2;
    sc_signal< sc_lv<1> > underflow_2_not_fu_487_p2;
    sc_signal< sc_lv<1> > brmerge_i_i_fu_481_p2;
    sc_signal< sc_lv<1> > brmerge_fu_493_p2;
    sc_signal< sc_lv<18> > p_Val2_5_mux_fu_499_p3;
    sc_signal< sc_lv<18> > p_Val2_5_fu_506_p3;
    sc_signal< sc_logic > grp_fu_263_ce;
    sc_signal< sc_lv<9> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<9> ap_ST_st1_fsm_0;
    static const sc_lv<9> ap_ST_st2_fsm_1;
    static const sc_lv<9> ap_ST_st3_fsm_2;
    static const sc_lv<9> ap_ST_st4_fsm_3;
    static const sc_lv<9> ap_ST_st5_fsm_4;
    static const sc_lv<9> ap_ST_st6_fsm_5;
    static const sc_lv<9> ap_ST_st7_fsm_6;
    static const sc_lv<9> ap_ST_st8_fsm_7;
    static const sc_lv<9> ap_ST_st9_fsm_8;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<39> ap_const_lv39_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<7> ap_const_lv7_7F;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<8> ap_const_lv8_80;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_22;
    static const sc_lv<32> ap_const_lv32_23;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<32> ap_const_lv32_26;
    static const sc_lv<3> ap_const_lv3_7;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<17> ap_const_lv17_0;
    static const sc_lv<18> ap_const_lv18_1FFFF;
    static const sc_lv<18> ap_const_lv18_20001;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Range1_all_ones_fu_360_p2();
    void thread_Range1_all_zeros_fu_366_p2();
    void thread_Range2_all_ones_fu_344_p2();
    void thread_accu_V_fu_273_p2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_105();
    void thread_ap_sig_bdd_114();
    void thread_ap_sig_bdd_133();
    void thread_ap_sig_bdd_154();
    void thread_ap_sig_bdd_25();
    void thread_ap_sig_bdd_59();
    void thread_ap_sig_bdd_74();
    void thread_ap_sig_bdd_94();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_brmerge40_demorgan_i_fu_418_p2();
    void thread_brmerge40_i_fu_424_p2();
    void thread_brmerge_fu_493_p2();
    void thread_brmerge_i_fu_412_p2();
    void thread_brmerge_i_i_fu_481_p2();
    void thread_carry_fu_320_p2();
    void thread_coeff_hw_V_address0();
    void thread_coeff_hw_V_ce0();
    void thread_deleted_ones_fu_392_p3();
    void thread_deleted_zeros_fu_372_p3();
    void thread_exitcond1_fu_177_p2();
    void thread_exitcond_fu_199_p2();
    void thread_grp_fu_263_ce();
    void thread_grp_fu_263_p0();
    void thread_grp_fu_263_p1();
    void thread_i_1_fu_183_p2();
    void thread_i_2_fu_205_p2();
    void thread_newsignbit_fu_306_p3();
    void thread_overflow_fu_465_p2();
    void thread_p_38_i_fu_400_p2();
    void thread_p_41_i_fu_386_p2();
    void thread_p_Val2_1_fu_279_p4();
    void thread_p_Val2_2_fu_300_p2();
    void thread_p_Val2_5_fu_506_p3();
    void thread_p_Val2_5_mux_fu_499_p3();
    void thread_p_not_i_fu_406_p2();
    void thread_qb_assign_1_fu_249_p2();
    void thread_qbit_fu_217_p3();
    void thread_r_fu_229_p2();
    void thread_r_i_i_fu_243_p2();
    void thread_res_V();
    void thread_res_V_ap_vld();
    void thread_signbit_fu_446_p3();
    void thread_smpl_V_address0();
    void thread_smpl_V_ce0();
    void thread_smpl_V_d0();
    void thread_smpl_V_we0();
    void thread_tmp2_fu_470_p2();
    void thread_tmp_10_fu_440_p2();
    void thread_tmp_14_fu_225_p1();
    void thread_tmp_15_fu_289_p3();
    void thread_tmp_16_fu_235_p3();
    void thread_tmp_18_fu_326_p3();
    void thread_tmp_19_fu_430_p1();
    void thread_tmp_1_fu_211_p1();
    void thread_tmp_2_fu_189_p1();
    void thread_tmp_3_fu_459_p2();
    void thread_tmp_4_fu_350_p4();
    void thread_tmp_5_fu_434_p2();
    void thread_tmp_6_fu_314_p2();
    void thread_tmp_7_fu_380_p2();
    void thread_tmp_8_fu_454_p2();
    void thread_tmp_9_cast_fu_269_p1();
    void thread_tmp_9_fu_334_p4();
    void thread_tmp_fu_194_p1();
    void thread_tmp_s_fu_297_p1();
    void thread_underflow_2_not_fu_487_p2();
    void thread_underflow_fu_475_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
